---
# https://pre-commit.com/hooks.html
repos:
  ###########
  # GENERAL #
  ###########

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [css, html, json, markdown, yaml]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint

  ######
  # F# #
  ######

  - repo: local
    hooks:
      - id: fantomas
        name: dotnet fantomas
        language: system
        entry: dotnet fantomas
        types: [file]
        files: \.(fs|fsx)$

  ###########
  # PYTHON #
  ###########

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # https://docs.astral.sh/ruff/integrations/#pre-commit
    rev: "v0.12.1" # Ruff version.
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.16.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        # args:
        #   - "--ignore-missing-imports"
        #   - "--explicit-package-bases"
        #   - "--scripts-are-modules"
        pass_filenames: false
        additional_dependencies:
          - alembic
          - pydantic
          - types-pyyaml
          - types-ujson

  #########
  # SHELL #
  #########

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/maxwinterstein/shfmt-py
    rev: v3.11.0.2
    hooks:
      - id: shfmt
