#!/usr/bin/env bash
set -euo pipefail

echo >&2 "INFO: Starting $0"

if [ "$(uname -s)" != Darwin ]; then
  echo "INFO: Not Darwin; Skipping Homebrew install..."
  exit 0
fi

echo >&2 "INFO: Installing Homebrew..."
# https://brew.sh/
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo >&2 "INFO: Installed Homebrew"

HOMEBREW_PREFIX="/opt/homebrew"
HOMEBREW_BIN="${HOMEBREW_PREFIX}/bin"
HOMEBREW_SBIN="${HOMEBREW_PREFIX}/sbin"
HOMEBREW_MAN="${HOMEBREW_PREFIX}/share/man"
HOMEBREW_EXECUTABLE="${HOMEBREW_BIN}/brew"

if [ ! -x "${HOMEBREW_EXECUTABLE}" ]; then
  echo >&2 "WARNING: Homebrew not installed at ${HOMEBREW_EXECUTABLE}"
  exit 1
fi

echo >&2 "INFO: Installing Homebrew paths..."
HOMEBREW_GNU_COREUTILS_PREFIX="${HOMEBREW_PREFIX}/opt/coreutils/libexec"
HOMEBREW_GNU_COREUTILS_BIN="${HOMEBREW_GNU_COREUTILS_PREFIX}/gnubin"
HOMEBREW_GNU_COREUTILS_MAN="${HOMEBREW_GNU_COREUTILS_PREFIX}/gnuman"
HOMEBREW_GNU_AWK_PREFIX="${HOMEBREW_PREFIX}/opt/gawk/libexec"
HOMEBREW_GNU_AWK_BIN="${HOMEBREW_GNU_AWK_PREFIX}/gnubin"
HOMEBREW_GNU_AWK_MAN="${HOMEBREW_GNU_AWK_PREFIX}/gnuman"
HOMEBREW_GNU_GREP_PREFIX="${HOMEBREW_PREFIX}/opt/grep/libexec"
HOMEBREW_GNU_GREP_BIN="${HOMEBREW_GNU_GREP_PREFIX}/gnubin"
HOMEBREW_GNU_GREP_MAN="${HOMEBREW_GNU_GREP_PREFIX}/gnuman"
HOMEBREW_GNU_MAKE_PREFIX="${HOMEBREW_PREFIX}/opt/make/libexec"
HOMEBREW_GNU_MAKE_BIN="${HOMEBREW_GNU_MAKE_PREFIX}/gnubin"
HOMEBREW_GNU_MAKE_MAN="${HOMEBREW_GNU_MAKE_PREFIX}/gnuman"
HOMEBREW_GNU_SED_PREFIX="${HOMEBREW_PREFIX}/opt/gnu-sed/libexec"
HOMEBREW_GNU_SED_BIN="${HOMEBREW_GNU_SED_PREFIX}/gnubin"
HOMEBREW_GNU_SED_MAN="${HOMEBREW_GNU_SED_PREFIX}/gnuman"
HOMEBREW_GNU_TAR_PREFIX="${HOMEBREW_PREFIX}/opt/gnu-tar/libexec"
HOMEBREW_GNU_TAR_BIN="${HOMEBREW_GNU_TAR_PREFIX}/gnubin"
HOMEBREW_GNU_TAR_MAN="${HOMEBREW_GNU_TAR_PREFIX}/gnuman"

sudo tee /etc/paths.d/50-homebrew <<-EOF
${HOMEBREW_GNU_COREUTILS_BIN}
${HOMEBREW_GNU_AWK_BIN}
${HOMEBREW_GNU_GREP_BIN}
${HOMEBREW_GNU_MAKE_BIN}
${HOMEBREW_GNU_SED_BIN}
${HOMEBREW_GNU_TAR_BIN}
${HOMEBREW_BIN}
${HOMEBREW_SBIN}
EOF
sudo tee /etc/manpaths.d/50-homebrew <<-EOF
${HOMEBREW_GNU_COREUTILS_MAN}
${HOMEBREW_GNU_AWK_MAN}
${HOMEBREW_GNU_GREP_MAN}
${HOMEBREW_GNU_MAKE_MAN}
${HOMEBREW_GNU_SED_MAN}
${HOMEBREW_GNU_TAR_MAN}
${HOMEBREW_MAN}
EOF
echo >&2 "INFO: Installed Homebrew paths"
