# https://mise.jdx.dev/configuration.html
# https://mise.jdx.dev/mise-cookbook/python.html#a-python-project-with-virtualenv

min_version = "2024.9.5"


[settings]
# https://mise.jdx.dev/configuration/settings.html

experimental = true

[settings.python]

# https://mise.jdx.dev/mise-cookbook/python.html#mise-uv
uv_venv_auto = true
venv_auto_create = true


[tools]
# https://mise.jdx.dev/dev-tools/
jq = "latest"
node = 'lts'
ollama = '0'
pre-commit = "latest"
# TODO: Python global with mise does not work for xonsh
# python = "{{ get_env(name='PYTHON_VERSION', default='3.12') }}"
uv = "latest"


[plugins]
#

[alias]
# https://mise.jdx.dev/dev-tools/aliases.html
