jq          1.8.1     ~/.config/mise/config.toml  latest
node        22.18.0
node        23.0.0
node        24.15.0   ~/.config/mise/config.toml  lts
ollama      0.22.0    ~/.config/mise/config.toml  0
poetry      2.4.1     ~/.config/mise/config.toml  latest
pre-commit  4.6.0     ~/.config/mise/config.toml  latest
python      3.12-dev
python      3.12.7
python      3.12.11
python      3.13.5
ruff        0.15.12   ~/.config/mise/config.toml  latest
uv          0.11.12   ~/.config/mise/config.toml  latest
