cask_args appdir: "/Applications"

# Taps
tap "ariga/tap"
tap "clintmod/formulas"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
tap "jesseduffield/lazygit"

# Fonts
cask "font-andale-mono"
cask "font-fira-code"
cask "font-inconsolata"
cask "font-iosevka"
cask "font-monofur-nerd-font"
cask "font-profontx"
cask "font-source-code-pro"

# Fun
brew "ack"
brew "archey4"
brew "ascii"
brew "cowsay"
brew "fortune"
brew "sl"

# Automation
brew "watchman"

# CLI
brew "bash"
brew "cdargs"
brew "cheat"
brew "chezmoi"
brew "colordiff"
brew "coreutils"
brew "direnv"
brew "gawk" # https://asdf-vm.com/guide/getting-started.html#_4-install-a-plugin
brew "gnu-sed"
brew "grc"
brew "gnu-tar"
#brew "clintmod/formulas/macprefs" # https://github.com/clintmod/macprefs/issues
brew "moreutils"
brew "neovim"
#brew "parallel" # already part of moreutils
brew "rust-parallel"
brew "the_silver_searcher" # ag
brew "tmux"
brew "xz"
brew "yadm"

# Linters
brew "markdownlint-cli"
brew "prettier"
brew "prettierd"
brew "proselint"
brew "terraform-ls"
brew "vint"

# TUI
brew "jp2a"
brew "libcaca"
brew "spaceman-diff"
brew "spark"
brew "tree"

# Search
brew "fzf"
brew "grep"
brew "ripgrep"

# Internet
brew "curl"
brew "dict"
brew "gdrive"
brew "httpie"
brew "nmap"
brew "openssh"
brew "rsync"
brew "squid"
brew "telnet"
brew "wget"
brew "youtube-dl"

# Security
brew "gpg" # https://asdf-vm.com/guide/getting-started.html#_4-install-a-plugin

# Programming
brew "git"
brew "jesseduffield/lazydocker/lazydocker"
brew "jesseduffield/lazygit/lazygit"
brew "just"
brew "make"
brew "pre-commit"
brew "source-highlight"
brew "watchexec"

# Infrastructure
brew "cloudflare-cli4"
brew "helm"
brew "kubernetes-cli"
brew "k9s"
brew "opentofu"
brew "s3cmd"
brew "terraform"
brew "terraform-docs"
brew "tflint"
brew "tfupdate"
brew "vultr"

# Databases
brew "dbmate"
brew "sqlite"
brew "sqlite3"

# Languages
brew "asdf"

# CSV
brew "csvq"

# F# (.NET)
cask "dotnet-sdk"

# Go
brew "go"
brew "gopls"

# Haskell
#brew "haskell-stack"

# JSON
brew "jq"

# Javascript/Typescript
brew "typescript"
brew "typescript-language-server"
brew "yarn"

# OCampl
brew "opam"

# Python
brew "autopep8"
brew "flake8"
brew "gettext"
brew "isort"
brew "openssl"
brew "mypy"
brew "pandoc"
brew "poetry"
brew "pylint"
brew "python3"
brew "pyright"
brew "readline"
brew "zlib"

# Rust
brew "rust"
brew "rustup"
brew "rust-analyzer"

# Shell
brew "shellcheck"
brew "tcl-tk"
brew "xonsh"
brew "zsh"
brew "zsh-completions"

# YAML
brew "yq"

# Applications

cask "1password"
cask "1password-cli"
cask "amethyst"
cask "discord"
cask "docker"
cask "dropbox"
cask "firefox" # brew install --cask --adopt firefox
cask "freecad"
#cask "geektool"
cask "git-credential-manager"
#cask "gimp"
#cask "handbrake"
cask "hammerspoon"
#cask "haskell-platform"
#cask "inkscape"
cask "karabiner-elements"
#cask "kitty"
#cask "little-snitch"
cask "logseq"
#cask "macfuse"
#cask "macs-fan-control"
#cask "mailmate"
cask "notion"
cask "notion-calendar"
cask "notunes"
#cask "protonmail-bridge"
cask "protonvpn"
cask "signal"
cask "todoist"
#cask "transmission"
cask "wezterm"
cask "vlc"
